/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectindividual;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nat;
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.pack();
        
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(555, 420));
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Username");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 160, 142, 34);

        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 210, 142, 35);

        usernameField.setBackground(new java.awt.Color(204, 255, 255));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(usernameField);
        usernameField.setBounds(250, 160, 170, 30);

        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton);
        loginButton.setBounds(140, 280, 98, 42);

        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);
        cancelButton.setBounds(300, 280, 96, 42);

        passwordField.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.add(passwordField);
        passwordField.setBounds(250, 210, 170, 30);

        jLabel1.setFont(new java.awt.Font("Gabriola", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Welcome to the Olympus inner chat");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(80, 30, 420, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\sbouf\\OneDrive\\Documents\\Bootcamp\\Projects\\Individual no1\\olympus3.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 530, 430);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-4, -4, 540, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
       String username = usernameField.getText();
      
       String password = String.valueOf(passwordField.getPassword());
       takeDumpUsername(username);
       
       PreparedStatement pstm;
       ResultSet rs;
       String query = "select * from user_details where username=? and password=?";
        
       
       
       try{
           Connection con = mysqlConnector.connect();
           pstm = con.prepareStatement(query);
           

           
               pstm.setString(1, username);
               pstm.setString(2, password);
               rs = pstm.executeQuery();
 
           if (rs.next()){
               if (username.equals("nat")){
                   MainApp ma = new MainApp();
                   ma.setVisible(true);
                   this.dispose();
               }
               
               else if (username.equals("aphro")){
                   MainApp2Afro ma2 = new MainApp2Afro();
                   ma2.setVisible(true);
                   this.dispose();
               }
                
               else if (username.equals("pos")){
                   MainApp3Pos ma3 = new MainApp3Pos();
                   ma3.setVisible(true);
                   this.dispose();
               }
                else{
                     ChatView cv = new ChatView();
                     cv.setVisible(true);
                    this.dispose();
                     
                }
                   
                
               
               
               //JOptionPane.showMessageDialog(null, "Success");
               
               
           }
           //else{
               
              // JOptionPane.showMessageDialog(null, "Failed");           
           //}
          
       }
       catch (SQLException e){
        e.printStackTrace();

    }//GEN-LAST:event_loginButtonActionPerformed
    }
    
    
    
    public void takeDumpUsername(String DUMPusername){
    
    try{
    Connection con = mysqlConnector.connect();
     PreparedStatement pstm;
          
       
       ResultSet rs;
       String query = "update dump SET username_dump =? where id=1 ";
         pstm = con.prepareStatement(query);         
         pstm.setString(1,DUMPusername );
         pstm.executeUpdate();
         
        }catch(Exception e)
        { e.printStackTrace();
        
        }
       
       
         
    }
    
    
    
    
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed
  
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
