/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectindividual;

import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Nat;
 */
public class NewMsg extends javax.swing.JFrame {

    /**
     * Creates new form NewMsg
     */
    String username;
    
    public NewMsg() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();
        jmsg.setEditable(false);
        jmsg.setText(gettext());
        //fillCombo();
        fillComboMyMessage();
        
    }//allos constructor pernontas to username
    public NewMsg(String username){
        initComponents();
        this.username=username;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();
        jmsg.setEditable(false);
        jmsg.setText(gettext());
        //fillCombo();
        fillComboMyMessage();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jmsg = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        newchat = new javax.swing.JButton();
        backtologin = new javax.swing.JButton();
        backtoprof = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("My messages");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 10, 90, 42);

        jScrollPane1.setViewportView(jmsg);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(95, 172, 309, 126);

        jLabel5.setText("Sender..");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 70, 97, 30);

        newchat.setText("new chat");
        newchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newchatActionPerformed(evt);
            }
        });
        jPanel1.add(newchat);
        newchat.setBounds(87, 340, 82, 32);

        backtologin.setText("back to log in screen");
        backtologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtologinActionPerformed(evt);
            }
        });
        jPanel1.add(backtologin);
        backtologin.setBounds(329, 340, 148, 32);

        backtoprof.setText("back to profile");
        backtoprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoprofActionPerformed(evt);
            }
        });
        jPanel1.add(backtoprof);
        backtoprof.setBounds(200, 340, 111, 32);

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo);
        combo.setBounds(270, 70, 114, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sbouf\\OneDrive\\Documents\\Bootcamp\\Projects\\Individual no1\\olympus.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 140, 530, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newchatActionPerformed
       ChatView cv = new ChatView();
       cv.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_newchatActionPerformed

    private void backtoprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoprofActionPerformed
         if (fillCombo().equals("nat")){
                   MainApp ma = new MainApp();
                   ma.setVisible(true);
                   this.dispose();
               }
               
      else if (fillCombo().equals("aphro")){
                   MainApp2Afro ma2 = new MainApp2Afro();
                   ma2.setVisible(true);
                   this.dispose();
               }
                
      else if (fillCombo().equals("pos")){
                   MainApp3Pos ma3 = new MainApp3Pos();
                   ma3.setVisible(true);
                   this.dispose();
               }
                else{
                    LoginPage lp = new LoginPage();
                    lp.setVisible(true);
                    this.dispose();
                }
    }//GEN-LAST:event_backtoprofActionPerformed

    private void backtologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtologinActionPerformed
        LoginPage lp = new LoginPage();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backtologinActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
//        try {
//            String selectedUsername=(String)combo.getSelectedItem();
//                    Connection conn=mysqlConnector.connect();
//                    PreparedStatement ps=null;
//                    Resultset rs=null;
//                    ps=conn.prepareStatement("");
//                    jmsg.setText(gettext());
//                    fillCombo();
//        } catch (SQLException ex) {
//            Logger.getLogger(NewMsg.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMsg().setVisible(true);
            }
        });
    }
    
    /**
     *
     */
//    public void readornot(){
//        final int read=0;
        
       
   
    
     public String fillCombo(){
        
         
         try{
            Connection con = mysqlConnector.connect();
            
            String sql = "select * from user_details";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
            String name = rs.getString("username");
           
            combo.addItem(name);
             return name;
            } 
       
        }catch(Exception e){
   
        }return null; 
    }
     
     
     
     public void fillComboMyMessage(){
         
         ChatView cht = new ChatView();
         String currentName=cht.fillCombo1();
         try{
            Connection con = mysqlConnector.connect();
            
            String sql = "select DISTINCT sender from msges where receiver=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, currentName);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
            String name = rs.getString("sender");
           
            combo.addItem(name);
            // return name;
            } 
       
        }catch(Exception e){
   
        }
         //return null;
     }
 
     
     //
     
     private String gettext(){
         
          try{
            Connection con = mysqlConnector.connect();
            
            String sql = "select sender,msg_data,date_sub from msges where receiver=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, fillCombo()); //rwthsa kai autos to xei perasei ws username 
            //se auth th methodo theloume na paroume to minima analoga ton receiver
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
            String sender = rs.getString(1);            
            String msgdata = rs.getString(2);
            String date = rs.getString(3);
            
                //System.out.println(sender+" "+receiver+" "+msgdata+" "+date);
            
            
               return (sender+" "+msgdata+" "+date);       
            }
        
        }catch(Exception e){
                
   
        } 
       return null;
    } 
    
     
      public String valuethename(){
         String valuename = (String) combo.getSelectedItem();
         return valuename;
    }
     
     
    
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtologin;
    private javax.swing.JButton backtoprof;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jmsg;
    private javax.swing.JButton newchat;
    // End of variables declaration//GEN-END:variables
}
